package it.fleetmanager.repository.db.tools;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import it.fleetmanager.repository.db.H2DatabaseManager;

public class CreateTable {

    private static final Logger logger = LogManager.getLogger(CreateTable.class);

    public static void main(String[] args) {

        try (Connection conn = H2DatabaseManager.getInstance().getConnection();
             Statement stmt = conn.createStatement()) {

 

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS tipo_veicolo 
                AS ENUM ('AUTO','MOTO','FURGONE','CAMION');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS stato_veicolo 
                AS ENUM ('DISPONIBILE','PRENOTATO','IN_MANUTENZIONE','NON_DISPONIBILE');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS ruolo_utente 
                AS ENUM ('MANAGER','DRIVER');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS tipo_manutenzione 
                AS ENUM ('ORDINARIA','STRAORDINARIA','REVISIONE');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS stato_prenotazione 
                AS ENUM ('RICHIESTA','CONFERMATA','ATTIVA','ANNULLATA','COMPLETATA');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS tipo_prenotazione 
                AS ENUM ('UTENTE','MANUTENZIONE');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS tipo_scadenza 
                AS ENUM ('BOLLO','ASSICURAZIONE','REVISIONE','TAGLIANDO');
            """);

            stmt.execute("""
                CREATE TYPE IF NOT EXISTS tipo_notifica 
                AS ENUM ('SCADENZA','MANUTENZIONE','PRENOTAZIONE','SEGNALAZIONE');
            """);


            stmt.execute("""
                CREATE TABLE IF NOT EXISTS Veicolo (
                    targa VARCHAR(10) PRIMARY KEY,
                    tipoVeicolo tipo_veicolo NOT NULL,
                    marca VARCHAR(50) NOT NULL,
                    modello VARCHAR(50) NOT NULL,
                    annoImmatricolazione INT NOT NULL,
                    statoVeicolo stato_veicolo NOT NULL,
                    km INT NOT NULL
                );
            """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS Utente (
                    idUtente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(50) NOT NULL,
                    cognome VARCHAR(50) NOT NULL,
                    email VARCHAR(100) NOT NULL,
                    password VARCHAR(100) NOT NULL,
                    ruoloUtente ruolo_utente NOT NULL,
                    patente VARCHAR(20)
                );
            """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS Manutenzione (
                    idManutenzione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data TIMESTAMP NOT NULL,
                    tipoManutenzione tipo_manutenzione NOT NULL,
                    descrizione VARCHAR(255) NOT NULL,
                    targa VARCHAR(10) NOT NULL,
                    FOREIGN KEY (targa) REFERENCES Veicolo(targa) ON DELETE CASCADE
                );
            """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS Prenotazione (
                    idPrenotazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dataInizio TIMESTAMP NOT NULL,
                    dataFine TIMESTAMP NOT NULL,
                    statoPrenotazione stato_prenotazione NOT NULL,
                    tipoPrenotazione tipo_prenotazione NOT NULL,
                    idUtente INT NOT NULL,
                    targa VARCHAR(10) NOT NULL,
                    FOREIGN KEY (idUtente) REFERENCES Utente(idUtente) ON DELETE CASCADE,
                    FOREIGN KEY (targa) REFERENCES Veicolo(targa) ON DELETE CASCADE
                );
            """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS Scadenza (
                    idScadenza INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipoScadenza tipo_scadenza NOT NULL,
                    data DATE NOT NULL,
                    notificata BOOLEAN NOT NULL DEFAULT FALSE,
                    targa VARCHAR(10) NOT NULL,
                    FOREIGN KEY (targa) REFERENCES Veicolo(targa) ON DELETE CASCADE
                );
            """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS Notifica (
                    idNotifica INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tipoNotifica tipo_notifica NOT NULL,
                    messaggio VARCHAR(255) NOT NULL,
                    dataInvio TIMESTAMP NOT NULL,
                    letta BOOLEAN NOT NULL DEFAULT FALSE,
                    idUtente INT NOT NULL,
                    idScadenza INT,
                    FOREIGN KEY (idUtente) REFERENCES Utente(idUtente) ON DELETE CASCADE,
                    FOREIGN KEY (idScadenza) REFERENCES Scadenza(idScadenza) ON DELETE CASCADE
                );
            """);

            logger.info("Database creato correttamente.");

        } catch (SQLException e) {
            logger.error("Errore durante la creazione delle tabelle del database", e);
        }
    }
}
